#undef CPP_CHAR1
#undef CPP_INT8
#undef CPP_REAL4
#undef CPP_REAL8
#undef CPP_COMP4
#undef CPP_COMP8

#undef FORTRAN_CHAR1
#undef FORTRAN_INT8
#undef FORTRAN_REAL4
#undef FORTRAN_REAL8
#undef FORTRAN_COMP4
#undef FORTRAN_COMP8

#undef REAL4_SELECT2
#undef REAL8_SELECT2
#undef COMP4_SELECT1
#undef COMP8_SELECT1

} // extern "C"
